version: '3.7'

services:
  mongo:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - '27017:27017'
    logging:
      driver: none
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    command: npm run dev
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
