FROM node:10.16-alpine

RUN apk --no-cache add --virtual builds-deps build-base python
RUN apk add --no-cache bash

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package.json .
COPY package-lock.json .

RUN npm install

# Copy app source code
COPY . .

# Exports
EXPOSE 8000

CMD ["npm", "run", "start:dev"]